version: '3.8'

services:
  backend:
    build: .
    restart: always
    volumes:
      - backend_static:/app/static/
      - media_value:/app/media/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: mybase
    ports:
      - "5433:5432"

  nginx:
    image: nginx:1.26.1
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - backend_static:/app/static/
      - media_value:/app/media/
    ports:
      - "80:80"
    depends_on:
      - backend



volumes:
  backend_static:
  media_value:
